openapi: 3.0.1
info:
  title: Map-It!
  description: Draws a map with specific locations as markers.
  version: "v1.1"
servers:
  - url: https://roboguide.xyz/map-it
paths:
  /map:
    get:
      operationId: getMap
      summary: Returns a map with with specific locations as markers. Each marker has a location, index (single digit optional) and color (optional). Map is returned as a base64 image.
      parameters:
        - in: query
          name: places
          schema:
            type: string
            description: Semicolon separated list of geographical places to be shown on the map. Each place's parameters are divided by '|', in the order of name, number, and color.
            example: "Boston|1|red;NYC|2|blue"
        - in: query
          name: size
          schema:
            type: string
            description: The size of the map. Can be 'small', 'medium', or 'large'.
components:
  schemas:
    Place:
      type: object
      properties:
        name:
          type: string
          description: The name of the place.
        number:
          type: string
          description: The number associated with the place.
          nullable: true
        color:
          type: string
          description: The color of the place marker on the map.
          nullable: true
    PlacesList:
      type: array
      items:
        $ref: "#/components/schemas/Place"
